micronaut:
  application:
    name: pix
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    servidorGrpc:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10